### ISSUE TITLE
Structured data records are not showing in Network Request

### ISSUE THREAD

**Issue by roanlibelo** [run-crank/cog-web#102]
## Repro Steps:
```yml
scenario: Network Request Test
description: This checks some of the finished network requests of https://www.onupkeep.com/

steps:
- step: When I navigate to https://www.onupkeep.com/2
- step: Then there should be 1 matching network request for https://app.coview.com
  data:
    pathContains: /api/client-info/launchers
    withParameters:
      projectKey: Av-EzYN98DI
- step: And there should be 3 matching network request for https://api-iam.intercom.io
  data:
    pathContains: /messenger/web/conversations
    withParameters:
      page_title: CMMS Software by UpKeep CMMS | Try Free
- step: And there should be 15 matching network request for https://js.intercomcdn.com
- step: And there should be 1 matching network request for https://pi.pardot.com
  data:
    withParameters:
     account_id: 501441

```

## Actual Result:
Currently, it's only showing the network requests without the parameters.
![image](https://user-images.githubusercontent.com/54615569/75966302-1204c880-5f05-11ea-9c67-f9ce48df782b.png)

## Expected Result:
Structured data records should be displayed
