### ISSUE TITLE
Structured Data Records on LightHouse is not appearing properly

### ISSUE THREAD

**Issue by roanlibelo** [run-crank/cog-web#103]
## Repro Steps:
```yml
scenario: Lighthouse Performance score Test
description: This checks the Page's Lighthouse performance score

steps:
- step: When I navigate to https://app-ab29.marketo.com/#SL1005B2
- step: Then the desktop lighthouse performance score should be 70 or higher
- step: Then the mobile lighthouse performance score should be 60 or higher

```

## Actual Result:
![image](https://user-images.githubusercontent.com/54615569/75967214-770cee00-5f06-11ea-9f60-b63c647a2261.png)

## Expected Result:
Data records should appear properly in cmd.
