### ISSUE TITLE
Old error messages should be removed

### ISSUE THREAD

**Issue by roanlibelo** [run-crank/cog-web#104]
Since the error messages will also display the structured data, old error messages should be removed.

## Repro Steps:
```yml
scenario: Lighthouse Performance score Test
description: This checks the Page's Lighthouse performance score

steps:
- step: When I navigate to https://app-ab29.marketo.com/#SL1005B2
- step: Then the desktop lighthouse performance score should be 70 or higher
- step: Then the mobile lighthouse performance score should be 60 or higher

```

## Actual Result:
![image](https://user-images.githubusercontent.com/54615569/75966302-1204c880-5f05-11ea-9c67-f9ce48df782b.png)
![image](https://user-images.githubusercontent.com/54615569/76066166-04644700-5fc8-11ea-95ff-8ea041db537f.png)

## Expected Result:
Old error messages should be removed
