### ISSUE TITLE
Implement a "GA Event Tracked" Step

### ISSUE THREAD

**Issue by iamEAP** [run-crank/cog-web#11]
## Problem / Motivation
Another common hit type tracked in Google Analytics is an `event`.  We should expose a step that validates that an event is fired / tracked for a given Tracking ID / Measurement ID.

## Scope / UAT Target
- [ ] There should be a `GoogleAnalyticsAwareMixin` class applied to the `ClientWrapper` where network request logic should live.
- [ ] There should be a step (with proposed metadata below) that checks for a finished network request that match the following criteria:
  - [ ] A `GET` request
  - [ ] To URL beginning with `https://www.google-analytics.com`
  - [ ] Whose path contains `/collect` (could just be `/collect`, could be `/r/collect`, could be `/g/collect`, could be something similar...  best to keep it flexible for now).
  - [ ] Whose query string contains `t=event`
  - [ ] And whose query string contains `tid=[GA-Tracking-ID]`
  - [ ] And whose query string contains `ec=[UrlEncodedEventCategory]`
  - [ ] And whose query string contains `ea=[UrlEncodedEventAction]`
- [ ] If there are zero (or more than one) finished network requests that match the above criteria, a `fail` should be sent with message `Expected to track 1 GA event, but there were actually %d`
- [ ] If a `withParameters` object was provided, it should iterate through the parameters and ensure they were provided in the query string of the matching network request above (ensuring to URI Encode the value before checking, e.g. via `encodeURIComponent()`
  - [ ] If any check fails, then the step should respond with a `fail` message `Expected %s parameter on event to be %s, but it was actually %s`

## Proposed Step Metadata

**Proposed Step Name**: `Check that Google Analytics tracked an event`
**Proposed Step Expression**: `google analytics should have tracked an event with category (?<ec>.+) and action (?<ea>.+) for tracking id (?<id>[a-zA-Z0-9\-]+)`

**Proposed Step Fields**:
- `ec` (type `STRING`), label `Event Category`
- `ea` (type `STRING`), label `Event Action`
- `id` (type `STRING`), label `Tracking / Measurement ID` associated with the GA instance/property (e.g. `UA-75228722-5`)
- `withParameters` (type `MAP`), label `Parameter Checks`, an optional map of [Google Analytics Measurement Protocol Parameters](https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#dp) and their expected values.

## QA Scenarios
```yml
scenario: GA CTA click check
description: Proves that a GA event is triggered after a CTA is clicked

steps:
- step: Given I navigate to https://marketingplatform.google.com/about/analytics/
- step: When I click .gmp-header .h-c-header__cta-li--primary a
- step: Then google analytics should have tracked an event with category gmp: product: analytics: overview and action sign up cta for tracking id UA-1509844-34
  data:
    withParameters:
      el: sub nav
```

```yml
scenario: GA scroll depth check
description: Proves that a GA event is triggered after a page is scrolled a certain percentage

steps:
- step: Given I navigate to https://www.optimizesmart.com/scroll-tracking-via-scroll-depth-trigger-in-google-tag-manager/
- step: When I scroll through 50% of the page
- step: Then google analytics should have tracked an event with category Scroll Tracking and action /scroll-tracking-via-scroll-depth-trigger-in-google-tag-manager/ for tracking id UA-1509844-34
  data:
    withParameters:
      el: 50% Scroll
```
