### ISSUE TITLE
Scroll step seems non deterministic

### ISSUE THREAD

**Issue by iamEAP** [run-crank/cog-web#21]
## Steps
1. Run the following scenario using the latest `crank` CLI and Web Cog:

```yml
scenario: Google Analytics Event UAT
description: |
  Proves that this step checks for a GA Custom Event
  ...For a Specific GA Tracking ID
  ...With custom parameter checks.

steps:
- step: Given I navigate to https://marketingplatform.google.com/about/analytics/
- step: When I scroll through 100% of the page
- step: "Then Google Analytics should have tracked an event with category gmp: product: analytics: overview and action scroll depth for tracking id UA-38676921-23"
  data:
    withParameters:
      el: scroll 100%
```

**Expected**: The scenario above should pass.

**Actual**: The scenario does not pass.  However, if I add a `waitFor` attribute to the last step, the scenario passes.  e.g.

```yml
- waitFor: 1
  step: "Then Google Analytics should have tracked an event with category gmp: product: analytics: overview and action scroll depth for tracking id UA-38676921-23"
  data:
    withParameters:
      el: scroll 100%
```
