### ISSUE TITLE
Unable to check GA events whose actions/categories contain uppercase letters

### ISSUE THREAD

**Issue by iamEAP** [run-crank/cog-web#31]
## Repro Scenario
```yml
scenario: Uppercase Event Category/Action UAT

steps:
- step: Given I navigate to https://www.tableau.com/pricing/individual
- step: When I click the page element a.cta.p13n-buy-button
- step: Then Google Analytics should have tracked an event with category link and action BUY NOW for tracking id UA-625217-46

```

**Expected**: A passing test scenario

**Actual**: 

![Screen Shot 2019-10-25 at 5 33 25 PM](https://user-images.githubusercontent.com/3496491/67611317-a12af400-f74d-11e9-86ae-1475fa20045b.png)

^ Note also the `[object Object]` in the error message
