### ISSUE TITLE
Possible overwhelming wall of text when GA check fails

### ISSUE THREAD

**Issue by iamEAP** [run-crank/cog-web#32]
## Repro Scenario
```yml
scenario: Wall of Text

steps:
- step: Given I navigate to https://www.tableau.com
- step: Then Google Analytics should have tracked an event with category Doesn't and action Matter for tracking id UA-123456-1
```

**Expected**: 
- Error message to be accurate, perhaps: `Expected 1 matching GA event, but 0 matched:`
- More readable error message. Consider separating URLs with two newlines.

**Actual**:
![Screen Shot 2019-10-25 at 5 42 23 PM](https://user-images.githubusercontent.com/3496491/67611528-f0255900-f74e-11e9-8078-3ee3d37d3681.png)
