### ISSUE TITLE
TypeError:expectedParams[p].toLowerCase error is encountered when running a GA Event withParameters

### ISSUE THREAD

**Issue by roanlibelo** [run-crank/cog-web#36]
**Steps to Reproduce:**
1. Create a Google Analytics Event tracking scenario.
2. Make sure that you add withParameters.
3. Run the yml file and observe.

![image](https://user-images.githubusercontent.com/54615569/67672411-d84e0f00-f9b2-11e9-8867-cb0ef0215061.png)

**Actual Results:**
Test is failing when GA event tracking scenario has withParameters.

**Expected Results:**
Test should pass regardless if I have withParameters or not.

_**QA Scenarios:**_
```yml
scenario: Google Analytics Event Tracking
description: |
  Proves that this step checks for a GA Custom Event
  ...For a Specific GA Tracking ID
  ...With custom parameter checks.

steps:
- step: "Given I navigate to https://marketingplatform.google.com/about/analytics/"
- step: When I click the page element [href="https://analytics.google.com/analytics/web/?authuser=0#/provision/SignUp"]
- step: "Then Google Analytics should have tracked an event with category gmp: product: analytics: overview and action sign up cta for tracking id UA-38676921-23"
  data:
    withParameters:
      cid: 879436755.1571909785
```
