### ISSUE TITLE
Network requests error log is not showing anymore if there's zero matches

### ISSUE THREAD

**Issue by roanlibelo** [run-crank/cog-web#38]
**Steps to Reproduce:**
```yml
scenario: Google Analytics Event Tracking
description: |
  Proves that this step checks for a GA Custom Event
  ...For a Specific GA Tracking ID
  ...With custom parameter checks.

steps:
- step: "Given I navigate to https://www.tableau.com/products/trial"
- step: When I click the page element [href="/academic/students#form"]
- step: "Then Google Analytics should have tracked an event with category form and action form present for tracking id UA-625217-46"
  data:
    withParameters:
      dt: "Start a Free Tableau Trial: Downloadsyyy your trial here"
```
old version:
![image](https://user-images.githubusercontent.com/54615569/67764375-cb99eb80-fa84-11e9-95f8-aa21d0b7430c.png)

new version:
![image](https://user-images.githubusercontent.com/54615569/67764398-d3f22680-fa84-11e9-866a-ddb41bf30012.png)

**Actual Result:**
Network error logs are not showing anymore on the latest web version.

**Expected Result:**
It should show a list of network requests error.
