### ISSUE TITLE
New Step: Check that a Google Floodlight tag fired

### ISSUE THREAD

**Issue by iamEAP** [run-crank/cog-web#64]
## Scope / UAT Target
- [x] `GoogleAdsAware` mixin containing network logic.
- [x] There should be a step (with proposed metadata below) that checks for a finished network request that matches the following criteria:
  - [x] To a URL with host containing `fls.doubleclick.net` or `ad.doubleclick.net`
  - [x] Whose path contains a `src` whose value is an integer representing a given Advertiser ID.
  - [x] And whose path contains a `type` whose value is string representing a given Activity Group.
  - [x] And whose path contains a `cat` whose value is a string representing a given Activity.
  - [x] If an optional `cMethod` (Conversion Method) parameter is provided, these additional checks are performed:
    - [x] When the conversion method is `standard`...
      - [x] The path should contain an `ord` whose value is numeric and is not the literal value `1`
      - [x] The path should not contain a `num`
    - [x] When the conversion method is `unique`...
      - [x] The path should contain an `ord` whose value is exactly `1`
      - [x] The path should contain a `num` whose value is numeric and is not the literal value `1`
    - [x] When the conversion method is `session`...
      - [x] The path should contain an `ord` whose value is not the literal value `1`
      - [x] The path should not contain a `num`
  - [x] If optional `withVariables` data is provided, the path should be checked for their existence and values.
- [x] If there are zero finished network requests that match the above criteria, a `fail` should be sent with message `Expected Floodlight tag to fire for advertiser %d, group %s, and activity %s, but no Floodlight tag fire was detected.`
- [x] If a network request matched the URL host, but not the parameters, the step should respond with a `fail` and a similar message, but including the list of matched network requests (similar to the GA steps)
- [x] ~~If more than one network request matched all criteria, a `error` should be sent with message `More than one Floodlight tag met the given criteria:\n\n%s` (where `%s` is a newline separate list of matched network request URLs, similar to the GA steps)~~ This may not be valid.
- [x] If a network request matches all criteria except for the constraints as defined by a provided `cMethod` value, the step should respond with a `fail` and message like `A floodlight tag fire was detected for advertiser %d, group %s, and activity %s, but it did not conform to the %s conversion count method.\n\n%s` (where the final `%s` is the full URL of the detected network request)

## Proposed Step Metadata

**Proposed Step Name**: `Check that a Google Floodlight tag fired`
**Proposed Step Expression**: `a floodlight tag should have fired for advertiser (?<aid>\\d+), group (?<group>[a-zA-Z0-9-_]+), and activity (?<atag>[a-zA-Z0-9-_]+)`

**Proposed Step Fields**:
- `aid` (type `NUMERIC`, required), label `Advertiser ID`
- `group` (type `STRING`, required), label `Group Tag String`
- `atag` (type `STRING`, required), label `Activity Tag String`
- `cMethod` (type `STRING`, optional) label `Counting Method (standard, unique, per session)`
- `withVariables` (type `MAP`, optional) Custom Variables, an optional map of variable names and their expected values

## Sample Scenario Steps
```yml 
- step: When I navigate to https://www.workfront.com
- step: Then a floodlight tag should have fired for advertiser 9230367, group workf0, and activity homep0
  data:
    cMethod: standard      
```

```yml
- step: When I navigate to https://www.tableau.com/trial/tableau-software
- step: Then a floodlight tag should have fired for advertiser 8292931, group all, and activity 20glo0
  data:
    cMethod: unique
    withVariables:
      u8: All - Audience Roles
```

## References
- [Floodlight Troubleshooting Guide](https://support.google.com/searchads/answer/2828176?hl=en&ref_topic=2478218)
