### ISSUE TITLE
Generic network request step should more gracefully handle content types

### ISSUE THREAD

**Issue by iamEAP** [run-crank/cog-web#76]
1. We should accept content types that _contain_ `application/x-www-form-urlencoded` and `application/json`, regardless of any other charset provided.

```yml
# Expected: PASS
# Actual: Unknown Content Type: application/x-www-form-urlencoded; charset=UTF-8
- step: When I navigate to https://pantheon.io
- step: There should be 1 matching network request for https://app.hushly.com
  data:
    pathContains: /runtime/widgets/57305
    withParameters:
      aid: 57305
```

2. We should allow network requests to be checked where the content type contains `text/plain`, and the body parses as valid JSON.

```
# Expected: PASS
# Actual: Unknown Content Type: text/plain
- step: When I navigate to https://pantheon.io
- step: There should be 1 matching network request for https://api.segment.io
  data:
    pathContains: /v1/p
    withParameters:
      writeKey: a1HMjl6WUcK4ToPKMjwu01BTbuaDHDr9
```
