### ISSUE TITLE
Test still passes even though Activity ID is incorrect

### ISSUE THREAD

**Issue by roanlibelo** [run-crank/cog-web#81]
##Repro Steps:
1. Run the yml file.
```yml 
- step: When I navigate to https://www.workfront.com
- step: Then a floodlight tag should have fired for advertiser 923036, group workf0, and activity homep0
  data:
    cMethod: standard      
```
## Actual Result:
![image](https://user-images.githubusercontent.com/54615569/74216851-a2723380-4ce0-11ea-8b39-c54c8184a256.png)
![image](https://user-images.githubusercontent.com/54615569/74216871-b027b900-4ce0-11ea-8b17-48183370c696.png)

## Expected Result:
Test should not pass since the correct Activity ID is 9230367
