### ISSUE TITLE
Implement a "click on [domQuerySelector]" step

### ISSUE THREAD

**Issue by iamEAP** [run-crank/cog-web#9]
## Problem / Motivation
It's common for marketers to trigger tags, scripts, and other analytics based on link clicks.  In order allow validation of events/state based on these actions, we will need to add a step representing this action.

## Scope / UAT Target
- [ ] There should be a step (with proposed metadata below) that clicks an element given a DOM Query Selector (with no additional expectations).
- [ ] Client interaction code should live in the `BasicInteractionAware` mixin introduced in #5

## Proposed Step Metadata

**Proposed Step Name**: `Click an element on a page`
**Proposed Step Expression**: `click on page element (?<domQuerySelector>.+)`

**Proposed Step Fields**:
- `domQuerySelector` (type `STRING`), label `Element's DOM Query Selector`

**Comment by amcpanaligan** [comment]
I am not sure how test or create a valid `scenario` for this. However, I can confirm when I watch through `puppeteer` that an element gets clicked

**Comment by iamEAP** [comment]
@amcpanaligan may I recommend something like...

```yml
steps:
- step: Given I navigate to https://crank.run
- step: When I click on page element .homepage-hero a[href="/intro"]
- step: Then the title meta tag on the current page should be Crank - Introduction
```

Kind of a meaningless test, but not completely unwarranted, given how Gatsby does navigation / pre-fetching ([e.g.](https://github.com/run-crank/run-crank.github.io/blob/7b44bf1/src/components/homepage-hero/index.js#L10))
