### ISSUE TITLE
Cannot read property "includes" of undefined when checking Google Floodlight

### ISSUE THREAD

**Issue by roanlibelo** [run-crank/cog-web#92]
## Repro Steps:
```yml 
- step: When I navigate to https://www.workfront.com
- step: Then a floodlight tag should have fired for advertiser 923036, group workf0, and activity homep0
  data:
    cMethod: standard      
```

## Actual Result:
![image](https://user-images.githubusercontent.com/54615569/74807878-7f6d0280-5324-11ea-8827-375324fd855f.png)

## Expected Result:
Test should pass
