### ISSUE TITLE
Google FloodLight step failed when ord value is decimal

### ISSUE THREAD

**Issue by roanlibelo** [run-crank/cog-web#98]
## Repro Steps:
```yml 
scenario: Google FloodLight - No Variables
description: This checks that a Google FloodLight tag fired works as expected even without parameters.

steps:
- step: When I navigate to https://newrelic.com/
- step: Then a floodlight tag should have fired for advertiser 9647137, group newre0, and activity newre0
  data:
    cMethod: standard      
```

## Actual Result:
cmethod: Standard
![image](https://user-images.githubusercontent.com/54615569/75229151-55b44f80-57ec-11ea-9b98-dcd1f4b6db0d.png)

cmethod: per session:
![image](https://user-images.githubusercontent.com/54615569/75229195-6cf33d00-57ec-11ea-9eda-cf559b200e21.png)

## Expected Result:
Test should pass
